#!/bin/bash

echo "APK: clean /tmp and reboot..."
echo ""
read -p "Do you want to clen and reboot first? (y/n): " answer
answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
if [[ "$answer" == "y" || "$answer" == "yes" ]]; then
    echo "You chose yes"
    rm -r /tmp/*
    wait
    reboot
elif [[ "$answer" == "n" || "$answer" == "no" ]]; then
    echo "Skip clean /tmp , keep going for build..."
else
    echo "Invalid input. Please enter 'y' or 'n'."
fi

bash ./FRAMEWORKS-UPDATE
sleep 2
bash ./PLASMA_STUFF
sleep 2
bash ./KDE_APPS

